# fly.toml app configuration file generated for jamboard on 2024-01-11T21:02:07+02:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "jamboard"
primary_region = "waw"

[build]

[http_service]
  internal_port = 3000
  force_https = true
  auto_stop_machines = false
  auto_start_machines = true
  min_machines_running = 0
  max_maxhines_running = 1
  processes = ["app"]

[[vm]]
  cpu_kind = "shared"
  cpus = 1
  memory_mb = 256

[mounts]
  source="myapp_data"
  destination="/data"
